application: findcracks
version: 1
runtime: python
api_version: 1

handlers:
- url: .*/
  script: main.py
  
- url: .*/find
  script: main.py

- url: /css
  static_dir: static/css/
- url: /js
  static_dir: static/js/
- url: /images
  static_dir: static/images/